Repository ironcore-dev/ipam, pull requests merged in 2024-03, with the labels that each got.

#285 Switch all internal references from onmetal to ironcore
  Makefile
  PROJECT
  README.md
  api/ipam/v1alpha1/doc.go
  api/ipam/v1alpha1/groupversion_info.go
  api/ipam/v1alpha1/ip_webhook.go
  api/ipam/v1alpha1/network_webhook.go
  api/ipam/v1alpha1/networkcounter_webhook.go
  api/ipam/v1alpha1/subnet_webhook.go
  charts/ipam/local.yaml
  charts/ipam/values.yaml
  clientgo/applyconfiguration/ipam/v1alpha1/ip.go
  clientgo/applyconfiguration/ipam/v1alpha1/network.go
  clientgo/applyconfiguration/ipam/v1alpha1/networkcounter.go
  clientgo/applyconfiguration/ipam/v1alpha1/subnet.go
  clientgo/applyconfiguration/utils.go
  clientgo/informers/generic.go
  clientgo/ipam/typed/ipam/v1alpha1/ipam_client.go
  config/crd/bases/ipam.ironcore.dev_ips.yaml
  config/crd/bases/ipam.ironcore.dev_networkcounters.yaml
  config/crd/bases/ipam.ironcore.dev_networks.yaml
  config/crd/bases/ipam.ironcore.dev_subnets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ips.yaml
  config/crd/patches/webhook_in_ips.yaml
  config/manager/controller_manager_config.yaml
  config/rbac/ip_editor_role.yaml
  config/rbac/ip_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/ipam_v1alpha1_geneve_network.yaml
  config/samples/ipam_v1alpha1_ipv4_child_bits_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_child_capacity_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_child_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_ip.yaml
  config/samples/ipam_v1alpha1_ipv4_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv4_parent_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_resource_and_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv4_resource_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_child_bits_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_child_capacity_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_child_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_parent_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_resource_and_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_resource_ip.yaml
  config/samples/ipam_v1alpha1_mpls_network.yaml
  config/samples/ipam_v1alpha1_network.yaml
  config/samples/ipam_v1alpha1_referred_networkcounter.yaml
  config/samples/ipam_v1alpha1_vxlan_network.yaml
  config/webhook/manifests.yaml
  controllers/ip_controller.go
  controllers/network_controller.go
  controllers/subnet_controller.go
  docs/development.md
  docs/installation.md
  docs/usage.md
  main.go
Labels: documentation, size/L

#286 Downgrade kube-openapi
  clientgo/openapi/zz_generated.openapi.go
  go.mod
  go.sum
Labels: bug, size/M

#292 Rename API group to `ipam.metal.ironcore.dev`
  api/ipam/v1alpha1/doc.go
  api/ipam/v1alpha1/groupversion_info.go
  api/ipam/v1alpha1/ip_webhook.go
  api/ipam/v1alpha1/network_webhook.go
  api/ipam/v1alpha1/networkcounter_webhook.go
  api/ipam/v1alpha1/subnet_webhook.go
  charts/ipam/local.yaml
  charts/ipam/values.yaml
  clientgo/applyconfiguration/ipam/v1alpha1/ip.go
  clientgo/applyconfiguration/ipam/v1alpha1/network.go
  clientgo/applyconfiguration/ipam/v1alpha1/networkcounter.go
  clientgo/applyconfiguration/ipam/v1alpha1/subnet.go
  clientgo/applyconfiguration/utils.go
  clientgo/informers/generic.go
  clientgo/ipam/typed/ipam/v1alpha1/ipam_client.go
  clientgo/openapi/zz_generated.openapi.go
  config/crd/bases/ipam.metal.ironcore.dev_ips.yaml
  config/crd/bases/ipam.metal.ironcore.dev_networkcounters.yaml
  config/crd/bases/ipam.metal.ironcore.dev_networks.yaml
  config/crd/bases/ipam.metal.ironcore.dev_subnets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ips.yaml
  config/crd/patches/webhook_in_ips.yaml
  config/rbac/ip_editor_role.yaml
  config/rbac/ip_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/ipam_v1alpha1_geneve_network.yaml
  config/samples/ipam_v1alpha1_ipv4_child_bits_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_child_capacity_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_child_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_ip.yaml
  config/samples/ipam_v1alpha1_ipv4_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv4_parent_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv4_resource_and_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv4_resource_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_child_bits_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_child_capacity_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_child_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_parent_cidr_subnet.yaml
  config/samples/ipam_v1alpha1_ipv6_resource_and_ip_ip.yaml
  config/samples/ipam_v1alpha1_ipv6_resource_ip.yaml
  config/samples/ipam_v1alpha1_mpls_network.yaml
  config/samples/ipam_v1alpha1_network.yaml
  config/samples/ipam_v1alpha1_referred_networkcounter.yaml
  config/samples/ipam_v1alpha1_vxlan_network.yaml
  config/webhook/manifests.yaml
  controllers/ip_controller.go
  controllers/network_controller.go
  controllers/subnet_controller.go
  docs/development.md
  docs/usage.md
Labels: documentation, enhancement, size/L
